In [1]:
import numpy as np

In [4]:
x = np.array([[1,0,0],[0,0,1],[1,0,1],[1,1,0]])
y = np.array([[0],[0],[0],[1]])

In [5]:
print(x)

[[1 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 0]]


In [6]:
w = np.random.random((3,1))
w

array([[0.86802584],
       [0.62317489],
       [0.82431634]])

In [8]:
sum = np.dot(x,w)+0.02
sum

array([[0.88802584],
       [0.84431634],
       [1.71234218],
       [1.51120073]])

In [9]:
yp = 1 / (1 + np.exp(-sum))
yp

array([[0.70848261],
       [0.69937351],
       [0.84713983],
       [0.81923909]])

In [11]:
yp.round()

array([[1.],
       [1.],
       [1.],
       [1.]])

In [12]:
error = y -yp
change_in_w = error * yp * (1-yp)
w = w + np.dot(x.T,change_in_w)
w

array([[0.63876814],
       [0.64994313],
       [0.56757344]])